//! Trace → Rust #[test] generator. Pure: string in, string out. The CLI handles
//! file I/O. Emits a self-contained tokio test that re-creates the session and
//! replays the captured mutations. Observation/state-restoring concerns are
//! deferred — this is a structural emitter, not a semantic one.

use crate::trace::TraceEntry;

pub fn to_rust(entries: &[TraceEntry], test_name: &str) -> String {
    let mut out = String::new();
    out.push_str("// Generated by inkapp-harness::emit::to_rust — do not hand-edit.\n");
    out.push_str("use inkapp_harness::session::Session;\n");
    out.push_str("use tempfile::tempdir;\n\n");
    out.push_str(&format!("#[tokio::test]\nasync fn {test_name}() {{\n"));
    out.push_str("    let dir = tempdir().unwrap();\n");
    out.push_str("    let mut s = Session::new_fake(dir.path()).await.unwrap();\n\n");

    let mut device_counter = 0;
    let mut last_dev_var: Option<String> = None;

    for entry in entries {
        match entry {
            TraceEntry::Call {
                cmd, args, result, ..
            } => {
                let cmd_pair: Vec<&str> = cmd.iter().map(|s| s.as_str()).collect();
                match cmd_pair.as_slice() {
                    ["device", "new"] => {
                        device_counter += 1;
                        let var = format!("dev_{device_counter}");
                        let name_arg = args
                            .get("name")
                            .and_then(|v| v.as_str())
                            .map(|n| format!("Some({n:?})"))
                            .unwrap_or_else(|| "None".to_string());
                        out.push_str(&format!(
                            "    let {var} = s.device_new({name_arg}).unwrap();\n"
                        ));
                        last_dev_var = Some(var);
                    }
                    ["document", "publish"] => {
                        let app_name = args
                            .get("app_name")
                            .and_then(|v| v.as_str())
                            .unwrap_or("unknown");
                        out.push_str(&format!(
                            "    /* TODO: re-publish app {app_name:?} — populate from app registry */\n"
                        ));
                        if let Some(id) = result.get("id").and_then(|v| v.as_str()) {
                            out.push_str(&format!("    let doc_id: &str = {id:?};\n"));
                        }
                    }
                    ["ink", "tap"] => {
                        let page = args.get("page").and_then(|v| v.as_u64()).unwrap_or(0);
                        let region = args.get("region").and_then(|v| v.as_str()).unwrap_or("");
                        let dev = last_dev_var.as_deref().unwrap_or("dev");
                        out.push_str(&format!(
                            "    s.ink_tap(&{dev}, doc_id, {page}, {region:?}).unwrap();\n"
                        ));
                    }
                    ["ink", "swipe"] => {
                        let page = args.get("page").and_then(|v| v.as_u64()).unwrap_or(0);
                        let region = args.get("region").and_then(|v| v.as_str()).unwrap_or("");
                        let dev = last_dev_var.as_deref().unwrap_or("dev");
                        out.push_str(&format!(
                            "    s.ink_swipe(&{dev}, doc_id, {page}, {region:?}).unwrap();\n"
                        ));
                    }
                    ["ink", "draw"] => {
                        let page = args.get("page").and_then(|v| v.as_u64()).unwrap_or(0);
                        let highlighter = args
                            .get("highlighter")
                            .and_then(|v| v.as_bool())
                            .unwrap_or(false);
                        let points_json = args.get("points").cloned().unwrap_or_default();
                        let dev = last_dev_var.as_deref().unwrap_or("dev");
                        out.push_str(&format!(
                            "    {{\n        use inkapp_core::geometry::PdfPoint;\n        let pts: Vec<PdfPoint> = serde_json::from_str(r#\"{points_json}\"#).unwrap();\n        s.ink_draw(&{dev}, doc_id, {page}, &pts, {highlighter}).unwrap();\n    }}\n",
                        ));
                    }
                    ["link", "follow"] => {
                        let page = args.get("page").and_then(|v| v.as_u64()).unwrap_or(0);
                        let region = args.get("region").and_then(|v| v.as_str()).unwrap_or("");
                        let dev = last_dev_var.as_deref().unwrap_or("dev");
                        out.push_str(&format!(
                            "    let _ = s.link_follow(&{dev}, doc_id, {page}, {region:?}).unwrap();\n"
                        ));
                    }
                    ["device", "sync"] => {
                        let dev = last_dev_var.as_deref().unwrap_or("dev");
                        out.push_str(&format!(
                            "    let _ = s.device_sync(&{dev}).await.unwrap();\n"
                        ));
                    }
                    ["session", "step"] => {
                        out.push_str(
                            "    /* session step: requires App; supply in dogfood harness */\n",
                        );
                    }
                    _ => {
                        out.push_str(&format!("    // skipped: {cmd:?}\n"));
                    }
                }
            }
            TraceEntry::Assert {
                target, expected, ..
            } => {
                out.push_str(&format!("    // assert {target} == {expected}\n"));
            }
        }
    }

    out.push_str("    let _ = (dir,);\n");
    out.push_str("}\n");
    out
}
